name = "src"
version = "0.1.0"
description = "A new project named 'src', managed by `axes`."

[scripts.test]
run = """echo "Test for '<axes::name>' successful!""""
desc = "Run a simple test echo command."

[options]
at_start = ""
at_exit = ""

[options.open_with]

[vars]
GREETING = "Hello from there!"

[env]
