name = "Axes"
version = "0.1.0"
description = "A new project managed by axes."

[commands]
hello = "echo 'Hello from {name}!'"
build = "{v_build}"
replace = "{v_replace}"
br = ["{v_build}", "{v_replace}", "echo 'Todo listo!'"]
testime = "Measure-Command {var_t}}" # Only powershell
collect = "collect --extensions .rs,.md,.toml --exclude examples,locales --content --output project_content_text.txt"

[options]

[vars]
v_build = "cargo build --release"
v_replace = "copy /Y {root}\\target\\release\\axes.exe C:\\scripts\\axes.exe"
var_t = "{ axes axes hello "

[env]
