# axes.toml for the 'axes' project
# This file defines the complete development, testing, and release workflow for `axes` itself.
# It is designed to be a best-practice example of a clean and maintainable configuration.

# === Project Metadata ===
# Version is synchronized with Cargo.toml and the application's version output.
version = "0.3.0-beta"
description = "The development workflow configuration for the `axes` project itself."

# === Development Scripts ===
# Defines workflows for building, testing, and managing the tool.
[scripts]
tests = 'echo <params(literal)> <params::flag(map="zzzz=", default="aaaa", required)>'
# --- Core Development Workflows ---
build = { desc = "Builds the project in debug mode with fast compilation.", run = "cargo build <params>" }
build_release = { desc = "Builds the project in release mode for distribution.", run = "cargo build --release <params::lang(map='--features lang_', default='es')>" }
run = { desc = "Runs the project, passing all arguments to the binary.", run = "cargo run -- <params>" }
test = { desc = "Runs all unit and integration tests.", run = "cargo test" }

# --- Code Quality ---
check = { desc = "Checks the project for errors without compiling.", run = "cargo check" }
lint = { desc = "Lints the code for style and correctness issues.", run = "cargo clippy -- -D warnings <params>" }
fmt = { desc = "Checks if the code is formatted according to project style.", run = "cargo fmt --all -- --check <params>" }
fmt_fix = { desc = "Formats the code automatically.", run = "cargo fmt --all <params>" }

# This is a composite script, showcasing the power of `axes` to create complete workflows.
quality = { desc = "Runs all quality checks in sequence (fmt, check, lint, test).", run = [
    "<scripts::fmt>",
    "> <scripts::check>",
    "> <scripts::lint>",
    "<scripts::test>",
]}

##_flamgraph_exec = { windows = "start flamegraph.svg", macos = "open flamegraph.svg", linux = "xdg-open flamegraph.svg", default="echo 'Flamegraph generated at flamegraph.svg'" }

# --- Artifacts & Distribution ---
clean = { desc = "Removes the target directory and build artifacts.", run = "cargo clean <params>" }
doc = { desc = "Builds and opens the project documentation in the browser.", run = "cargo doc --open <params>" }

[scripts._save_install]
windows = "powershell -Command \"New-Item -ItemType File -Path '<vars::install_path_win>' -Force | Out-Null; Copy-Item -Path '.\\target\\release\\axes.exe' -Destination '<vars::install_path_win>'\""
default = "install -m 755 -D \"<path>/target/release/axes\" \"<vars::install_path_nix>\""

# Builds and installs the artifact to a local path, showcasing a cross-platform script.
[scripts.install]
desc = "Builds in release and copies the artifact to a local installation path."
run = [
    "# Installing <#green>'axes'<#reset> on: <#blue>'<vars::install_path_win>'<#reset>...",
    "@<scripts::build_release>",
    "@<scripts::_save_install>",
    "# Completed.!"
]

# --- Performance Analysis ---
# This script generates a flamegraph and then opens it, showcasing a cross-platform sequence.
[scripts.flamegraph]
desc = "Generates a performance flamegraph for a given command and opens the result."
run = [
    "cargo flamegraph --bin axes -- <params::0(literal)>",
    "<scripts::_flamgraph_exec>"
]

# === Interpolation Variables ===
# Reusable values for maintaining consistency across scripts.
[vars]
# --- Installation Paths (User Configurable) ---
# By default, install into a local './bin' directory. This is safe and portable.
# A user can override this by creating a `.axes/axes.local.toml` file with:
install_path_win = "<params::0(default='.\\bin\\axes.exe')>" 
install_path_nix = "<params::0(default='./bin/axes')>"

# === Environment Variables ===
# Injected into every command executed by `axes`.s
[env]
RUST_LOG = "debug"   # Set a sensible default log level for `axes run`.
RUST_BACKTRACE = "1"  # Always show full backtraces in case of panic.
CARGO_PROFILE_RELEASE_DEBUG = "true" # Enable debug symbols in release builds for better profiling.