# === Project Metadata ===
# The name 'axes' is inherited from Cargo.toml, but we define it here for clarity as local name.
name = "axes"
version = "0.1.5-Alpha" # Synchronize with Cargo.toml
description = "The development workflow configuration for the `axes` project itself."

# === Development Scripts ===
# Defines workflows for building, testing, and managing the tool.
[scripts]
# Tests
hello = "echo Hello, World!"

test_q = "-comando info <axes::vars::_param_1> <axes::params::1(map='--info', default='algo')>"

test_w = [
    "-comando 1",
    "-comando 2",
    "-comando 3",
    "-comando 4"
]

test_vel = "./.axes/command_test.ps1 <axes::params>"

# --- Build Workflows ---
build = { desc = "Builds the project in debug mode with fast compilation.", run = "cargo build <axes::params>" }
build_release = { desc = "Builds the project in release mode for distribution.", run = "cargo build --release" }

# --- Run and Test Workflows ---
run = { desc = "Runs the project, passing all arguments to the binary.", run = "cargo run -- <axes::params>" }
test = { desc = "Runs all unit and integration tests.", run = "cargo test" }

# --- Code Quality Workflows ---
check = { desc = "Checks the project for errors without building.", run = "cargo check" }
lint = { desc = "Lints the code for style and correctness issues.", run = "cargo clippy <axes::vars::clippy_args> <axes::params>" }
fmt = { desc = "Checks if the code is formatted according to project style.", run = "cargo fmt <axes::params>" }
fmt_fix = { desc = "Formats the code automatically.", run = "cargo fmt --all <axes::params>" }

# --- Composite and Utility Workflows ---
quality = { desc = "Runs all quality checks in sequence (fmt, check, lint, test).", run = [
    "<axes::scripts::fmt>",
    "<axes::scripts::check>",
    "<axes::scripts::lint>",
    "<axes::scripts::test>",
]}
doc = { desc = "Builds and opens the project documentation in the browser.", run = "cargo doc --open <axes::params>" }
clean = { desc = "Removes the target directory and build artifacts.", run = "cargo clean <axes::params>" }

# --- Local Installation Workflow ---
_install = [
    "<axes::scripts::build_release>",
    "xcopy /Y \"<axes::path>\\target\\release\\axes.exe\" \"C:\\scripts\\axes.exe\""
]

[scripts.install]
desc = "Builds in release and copies the artifact to a local installation path."
windows = [
    "<axes::scripts::build_release>",
    # Uses `xcopy` to create the directory if it doesn't exist and suppress the prompt.
    "xcopy /Y \"<axes::path>\\target\\release\\axes.exe\" \"<axes::vars::install_path_win>\""
]
linux = [
    "<axes::scripts::build_release>",
    "install -m 755 -D \"<axes::path>/target/release/axes\" \"<axes::vars::install_path_nix>\""
]
macos = [
    "<axes::scripts::build_release>",
    "install -m 755 -D \"<axes::path>/target/release/axes\" \"<axes::vars::install_path_nix>\""
]

# === Interpolation Variables ===
# Reusable values in the scripts.
[vars]
# Standard arguments for clippy to ensure consistency.
clippy_args = "-- -D warnings"
_param_1 = "<axes::params::0(required)>"

# --- Installation Paths (User Configurable) ---
# NOTE: Change these paths to match a directory in your PATH.
install_path_win = "<axes::path>\\axes.exe" # Example for Windows # "C:\\scripts\\axes.exe"
install_path_nix = "/usr/local/bin/" # Example for Linux/macOS

# === Environment Variables ===
# Injected into every command executed by `axes`.
[env]
RUST_LOG = "debug" # Default log level when running with `axes run`.
RUST_BACKTRACE = "1" # Shows full backtraces in case of panic.