//! # Axes Language
//!
//! This crate provides the core functionality for the Axes language, including the CLI, constants, core logic, models, state management, and system interactions.

// The translations are generated by the build script and included here.
include!(concat!(env!("OUT_DIR"), "/translations.rs"));

use std::sync::Arc;
use std::sync::atomic::AtomicBool;

/// A type alias for a cancellation token, which is used to signal termination to long-running tasks.
pub type CancellationToken = Arc<AtomicBool>;

/// The command-line interface module, responsible for parsing arguments and handling user input.
pub mod cli;

/// The constants module, which contains various constants used throughout the crate.
pub mod constants;

/// The core module, which contains the main logic of the Axes language.
pub mod core;

/// The models module, which defines the data structures used in the crate.
pub mod models;

/// The state module, which manages the state of the application.
pub mod state;

/// The system module, which provides an interface to the underlying operating system.
pub mod system;
