name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
env:
  CARGO_TERM_COLOR: always

jobs:
  quality-checks:
    name: Code Formatting & Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Run linter (Clippy)
        run: cargo clippy --all-targets -- -D warnings
